cmake_minimum_required(VERSION 4.3)
project(cppproject)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(cppproject main.cpp)
add_executable(cpp_basics 2.cpp
        4.cpp)

add_executable(ds_01_seq_list data_structures/01_seq_list.cpp
        data_structures/16.cpp
        data_structures/1.cpp)
add_executable(ds_02_singly_linked_list data_structures/02_singly_linked_list.cpp)
add_executable(ds_03_stack_variants data_structures/03_stack_variants.cpp)
add_executable(ds_04_queue_variants data_structures/04_queue_variants.cpp)
add_executable(ds_05_binary_search_tree data_structures/05_binary_search_tree.cpp)
add_executable(ds_06_heap data_structures/06_heap.cpp)
add_executable(ds_07_union_find data_structures/07_union_find.cpp)
add_executable(ds_08_graph_adj_list data_structures/08_graph_adj_list.cpp)
add_executable(ds_09_sort_variants data_structures/09_sort_variants.cpp)
add_executable(ds_10_doubly_linked_list data_structures/10_doubly_linked_list.cpp)
add_executable(ds_11_circular_linked_list data_structures/11_circular_linked_list.cpp)
add_executable(ds_12_deque data_structures/12_deque.cpp)
add_executable(ds_14_hash_table data_structures/14_hash_table.cpp)
add_executable(ds_15_avl_tree data_structures/15_avl_tree.cpp)
add_executable(ds_16_string data_structures/16_string.cpp)
add_executable(ds_17_array_storage data_structures/17_array_storage.cpp)
add_executable(ds_18_special_matrix_compressed_storage data_structures/18_special_matrix_compressed_storage.cpp)
add_executable(ds_19_generalized_list data_structures/19_generalized_list.cpp)
add_executable(ds_20_binary_tree data_structures/20_binary_tree.cpp)
add_executable(ds_22_search data_structures/22_search.cpp)
add_executable(ds_26_threaded_binary_tree data_structures/26_threaded_binary_tree.cpp)
add_executable(ds_27_huffman_tree data_structures/27_huffman_tree.cpp)
add_executable(ds_28_graph_mst data_structures/28_graph_mst.cpp)
add_executable(ds_29_graph_shortest_path data_structures/29_graph_shortest_path.cpp)
add_executable(ds_30_graph_topological_sort_and_critical_path data_structures/30_graph_topological_sort_and_critical_path.cpp)
add_executable(ds_31_b_tree data_structures/31_b_tree.cpp)
add_executable(ds_32_b_plus_tree data_structures/32_b_plus_tree.cpp)
